# Generated by Django 4.2.1 on 2023-05-25 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0002_alter_product_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=20)),
                ("place", models.CharField(max_length=20)),
                ("data", models.CharField(max_length=20)),
                ("time", models.CharField(max_length=20)),
                ("image", models.ImageField(upload_to="images")),
                ("event_status", models.CharField(max_length=20)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Artista.artist"
                    ),
                ),
            ],
        ),
    ]
