# Generated by Django 4.2.1 on 2023-05-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0003_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="data",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_status",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="place",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.CharField(max_length=100),
        ),
    ]
