# Generated by Django 4.2.1 on 2023-05-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0004_alter_event_data_alter_event_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(max_length=500),
        ),
    ]
