# Generated by Django 4.2.1 on 2023-06-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0006_rename_data_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.DateField(max_length=100),
        ),
    ]
