# Generated by Django 4.2.1 on 2023-06-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0007_alter_event_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.CharField(max_length=100),
        ),
    ]
