# Generated by Django 4.2.1 on 2023-06-08 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0008_alter_event_date_alter_event_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("p_name", models.CharField(max_length=500)),
                ("quantity", models.CharField(max_length=500)),
                ("total_price", models.CharField(max_length=500)),
                ("cart_status", models.CharField(max_length=10)),
                ("image", models.ImageField(upload_to="images")),
                ("category", models.CharField(max_length=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Artista.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Artista.user"
                    ),
                ),
            ],
        ),
    ]
