# Generated by Django 4.2.1 on 2023-06-09 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0009_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("quantity", models.CharField(blank=True, max_length=500, null=True)),
                ("total_price", models.IntegerField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("category", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "order_status",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Artista.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Artista.user"
                    ),
                ),
            ],
        ),
    ]
