# Generated by Django 4.2.1 on 2023-06-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0010_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_type", models.CharField(max_length=20)),
                ("amount", models.CharField(max_length=20)),
                ("date", models.CharField(max_length=20)),
                ("payment_status", models.CharField(max_length=20)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Artista.user"
                    ),
                ),
            ],
        ),
    ]
