# Generated by Django 4.2.1 on 2023-06-10 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0011_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="learning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.CharField(max_length=20)),
                ("category", models.CharField(max_length=20)),
                ("video", models.FileField(upload_to="video/")),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Artista.artist"
                    ),
                ),
            ],
        ),
    ]
