# Generated by Django 4.2.1 on 2023-06-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0012_learning"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learning",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="learning",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
