# Generated by Django 4.2.1 on 2023-06-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0015_complaint"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="reply",
        ),
    ]
