# Generated by Django 4.2.1 on 2023-06-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0020_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="payment_type",
        ),
    ]
