# Generated by Django 4.2.1 on 2023-06-19 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0021_remove_payment_payment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="jobapply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("phn_no", models.CharField(max_length=20)),
                ("qualification", models.CharField(max_length=20)),
                ("experience", models.CharField(max_length=20)),
                ("image", models.ImageField(blank=True, null=True, upload_to="image")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Artista.user"
                    ),
                ),
            ],
        ),
    ]
