# Generated by Django 4.2.1 on 2023-06-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0022_jobapply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobapply",
            name="image",
            field=models.ImageField(default=1, upload_to="images"),
            preserve_default=False,
        ),
    ]
