# Generated by Django 4.2.1 on 2023-06-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0024_alter_jobapply_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="name",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
