# Generated by Django 4.2.1 on 2023-07-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0026_cart_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="expday",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="expday",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="expday",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
