# Generated by Django 4.2.1 on 2023-07-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Artista",
            "0028_chat_a_name_chat_reply_chat_u_name_complaint_a_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="complaint_status",
        ),
        migrations.RemoveField(
            model_name="complaint",
            name="reply",
        ),
        migrations.AddField(
            model_name="complaint",
            name="complaintstatus",
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
