# Generated by Django 4.2.1 on 2023-07-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0029_remove_complaint_complaint_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="reply",
            field=models.CharField(default="no reply", max_length=500),
        ),
    ]
