# Generated by Django 4.2.1 on 2023-07-21 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Artista", "0030_complaint_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="artist",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Artista.artist",
            ),
            preserve_default=False,
        ),
    ]
